### PR TITLE
1.20

### PR DESCRIPTION
**Pull request by mocksonline**
preversion

### CODE REVIEW

**Comment by mocksonline** [comment]
worked

**Comment by aleck099** [comment]
It's still 1.19.3 in gradle.properties?

**Comment by mocksonline** [comment]
> It's still 1.19.3 in gradle.properties?

Thank you for your reply, I forgot to upload it before, it has been changed.

**Comment by manjaroman2** [comment]
crashes when opening the entity selector menu in 1.20.1

**Comment by veloute** [comment]
at this point, why don't we, at least temporarily, move to a fork so we can stay current?

**Pull request closed without merging**
