### PR TITLE
1.20.6

### PR DESCRIPTION
**Pull request by manjaroman2**

### CODE REVIEW

**Comment by n0rbyt3** [comment]
Thanks, but the mod is discontinued. I've already built a version for 1.20.6 with some additional features. Unfortunately, the original author closed the issue. You can find my build here: https://github.com/adamviola/EntityOutliner/issues/23#issuecomment-2076697976

I also wanted to create a new mod based on this, but I need some more UI work which isn't that easy - especially if you need to adapt it for other versions.

**Comment by manjaroman2** [comment]
Wow, Github is so bad at displaying forks of projects...

**Comment by manjaroman2** [comment]
@n0rbyt3 what features did you add? i gave your project a star

**Comment by n0rbyt3** [comment]
Thank you! See https://github.com/adamviola/EntityOutliner/issues/23#issuecomment-1893143045 for details.

I also planned some more complex UI changes, but it's harder than I thought. Currently, there is also less time. :/

**Pull request closed without merging**
